import React from 'react';
import { Language } from './types';

// SVGs are handled as React Components in a separate file or inline if simple, 
// but for the sake of the user's original structure, we will define data here.

export const CONFIG = {
  energyFactors: { heizoel: 9.9, erdgas_h: 10.6, erdgas_l: 9.2, fluessiggas: 6.7, pellets: 4.9, strom: 1.0, keine: 0 } as Record<string, number>,
  defaultPrices: {
    heizoel: 1.03, erdgas_h: 1.166, erdgas_l: 1.012, // Calculated from original code
    fluessiggas: 0.70, pellets: 0.30, strom: 0.25, keine: 0
  } as Record<string, number>,
  priceSliderConfigs: {
    heizoel: { min: 0.50, max: 2.50, step: 0.01, unit: "€/Liter" },
    erdgas_h: { min: 0.50, max: 3.00, step: 0.01, unit: "€/m³" },
    erdgas_l: { min: 0.50, max: 3.00, step: 0.01, unit: "€/m³" },
    fluessiggas: { min: 0.40, max: 2.00, step: 0.01, unit: "€/Liter" },
    pellets: { min: 0.15, max: 0.80, step: 0.01, unit: "€/kg" },
    strom: { min: 0.15, max: 0.80, step: 0.01, unit: "€/kWh" },
    keine: { min: 0, max: 0, step: 0.01, unit: "" }
  } as Record<string, any>,
  defaultWirkungsgrade: {
    heizoel: 80, erdgas_h: 82, erdgas_l: 82, fluessiggas: 85, pellets: 88, strom: 100, keine: 100
  } as Record<string, number>,
  co2FactorsKwhInput: {
    heizoel: 0.269, erdgas_h: 0.202, erdgas_l: 0.202, fluessiggas: 0.230,
    pellets: 0.02, strom: 0.22, keine: 0
  } as Record<string, number>,
  stromCo2Faktor: 0.22,
  kgCo2ProFussballfeldWaldProJahr: 5600,
  klasseFactors: { alt_unsaniert: 200, alt_teilsaniert: 150, alt_saniert: 100, neubau: 70, niedrigenergie: 30 } as Record<string, number>,
  specificHeatLoad: { alt_unsaniert: 100, alt_teilsaniert: 70, alt_saniert: 50, neubau: 40, niedrigenergie: 30 } as Record<string, number>,
  heizkoerperventilatorEffekt: 5,
  solarYieldFactors: { flach: 350, roehren: 450 } as Record<string, number>,
  pvYieldFactor: 1000,
  pvRealismFactor: 0.4
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  de: {
    step1Title: "Schritt 1: Daten zur Altanlage",
    basisTitle: "Berechnungsgrundlage",
    basisText: "Bitte wählen Sie, ob die Berechnung auf Basis Ihrer beheizbaren Fläche oder Ihres bisherigen Verbrauchs erfolgen soll.",
    basisArea: "Flächenbasierte Berechnung",
    basisConsumption: "Verbrauchsbasierte Berechnung",
    yourConsumptionTitle: "Ihr Verbrauch",
    annualConsumptionLabel: "Jährlicher Verbrauch",
    yourPropertyTitle: "Ihre Immobilie",
    buildingClassLabel: "Gebäudeklasse",
    areaLabel: "Beheizbare Fläche (m²)",
    currentSystemTitle: "Ihr aktuelles Heizsystem",
    efficiencyOldLabel: "Wirkungsgrad Altanlage (%)",
    efficiencyOldDisclaimer: "Typischer Wert wird je nach Heizsystem vorausgewählt.",
    priceOldLabel: "Aktueller Preis je Einheit",
    step2Title: "Schritt 2: Neues System & Optimierung",
    heatpumpDataTitle: "Daten für Wärmepumpe",
    gridPriceLabel: "Netz-Strompreis für Wärmepumpe (€/kWh)",
    gridPriceDisclaimer: "Dieser Preis gilt auch für \"Altanlage Strom\".",
    floorHeatingShareLabel: "Anteil Fußbodenheizung an Wärmeabgabe (%)",
    floorHeatingShareDisclaimer: "Wird automatisch basierend auf Gebäudeklasse angepasst.",
    flowTempLabel: "Vorlauftemperatur (°C)",
    baseScopInfo: "Abgeleiteter Basis-SCOP:",
    optimizationsTitle: "Zusätzliche Optimierungen",
    optimizationsText: "Wählen Sie optionale Komponenten aus, um die Berechnung zu verfeinern.",
    fanEffectText: "Durch die Lüfter sinkt die benötigte Vorlauftemperatur auf",
    fanEffectScopText: "Der SCOP verbessert sich dadurch auf",
    solarTypeLabel: "Kollektortyp",
    solarAreaLabel: "Kollektorfläche der Solaranlage (m²)",
    solarYieldInfo: "Geschätzter Jahresertrag",
    solarDisclaimer: "Der Ertrag reduziert den Wärmebedarf, den die Heizung decken muss.",
    step3Title: "Schritt 3: Investition & Kosten",
    investmentTitle: "Investitionskosten & Förderung Wärmepumpe",
    investmentLabel: "Investitionskosten Wärmepumpe (inkl. Einbau) in €",
    investmentDisclaimer: "Durchschnitt: 15.000–30.000 €. Addieren Sie Kosten für Zusatz-Optimierungen.",
    fundingLabel: "Erwartete Förderungen (einmalig) in €",
    fundingDisclaimer: "Reduziert die effektiven Investitionskosten.",
    runningCostsTitle: "Laufende Kosten",
    maintenanceOldLabel: "Jährliche Wartungskosten Altanlage (€)",
    maintenanceNewLabel: "Jährliche Wartungskosten Wärmepumpe (€)",
    step4Title: "Schritt 4: Ihr Ergebnis",
    resultHeatDemand: "Nutzwärmebedarf (Altanlage)",
    resultCostsOld: "Aktuelle Heizkosten (Altanlage)",
    resultCo2Old: "CO₂-Emissionen (Altanlage)",
    resultHpPower: "Ungefähre Heizleistung Wärmepumpe",
    resultCop: "Angepasste JAZ/SCOP für WP",
    resultCostsNew: "Heizkosten mit Wärmepumpe",
    resultCostsNewBuild: "Voraussichtliche jährliche Betriebskosten",
    resultCo2New: "CO₂-Emissionen (Wärmepumpe)",
    resultSavingsAnnual: "Jährliche Ersparnis (Betriebskosten)",
    resultSavingsCo2: "Jährliche CO₂-Einsparung",
    resultSavingsCo2Eq: "entspricht ca. {value} Fußballfeldern Waldfläche pro Jahr.",
    resultAmortization: "Amortisationszeit (nach Förderung)",
    unitYear: "Jahr",
    unitYears: "Jahre",
    fanResultLabel: "Effekt durch Heizkörperlüfter",
    resultDisclaimer: "* Alle Werte sind ungefähre Richtwerte. Die empfohlene Heizleistung ist eine grobe Schätzung; eine detaillierte Heizlastberechnung durch einen Fachbetrieb ist für die korrekte Dimensionierung unerlässlich.",
    exportPdfButton: "PDF Exportieren",
    priceUpdateInfo: "Die Standard-Energiepreise im Rechner sind Richtwerte (Stand: Juni 2025) und sollten für eine genaue Berechnung mit Ihren aktuellen Tarifen abgeglichen werden.",
    prevBtn: "Zurück",
    nextBtn: "Weiter",
    pdfExports: "PDF Exporte",
    configId: "Konfigurations-Nr.",
    amortizationNone: "Keine Amortisation",
    amortizationImmediate: "Sofort",
    amortizationNotApplicable: "Nicht anwendbar",
    pdfTitle: "Analyse Ihrer Heizkostenersparnis",
    pdfInputsTitle: "Ihre Eingaben",
    pdfResultsTitle: "Ihr Ergebnis",
    pdfFooter: "Berechnung erstellt am {date}. Konfigurations-Nr.: {id}. Alle Angaben sind Schätzungen ohne Gewähr.",
    commentaryTitle: "Interpretation der Ergebnisse"
  },
  en: {
    step1Title: "Step 1: Old System Data",
    basisTitle: "Calculation Basis",
    basisText: "Please choose whether the calculation should be based on your heatable area or your previous consumption.",
    basisArea: "Area-Based Calculation",
    basisConsumption: "Consumption-Based Calculation",
    yourConsumptionTitle: "Your Consumption",
    annualConsumptionLabel: "Annual Consumption",
    yourPropertyTitle: "Your Property",
    buildingClassLabel: "Building Class",
    areaLabel: "Heatable Area (m²)",
    currentSystemTitle: "Your Current Heating System",
    efficiencyOldLabel: "Efficiency of Old System (%)",
    efficiencyOldDisclaimer: "A typical value is pre-selected based on the heating system.",
    priceOldLabel: "Current Price per Unit",
    step2Title: "Step 2: New System & Optimization",
    heatpumpDataTitle: "Heat Pump Data",
    gridPriceLabel: "Grid Electricity Price for Heat Pump (€/kWh)",
    gridPriceDisclaimer: "This price also applies to \"Old System Electricity\".",
    floorHeatingShareLabel: "Share of Underfloor Heating in Heat Distribution (%)",
    floorHeatingShareDisclaimer: "Adjusted automatically based on building class.",
    flowTempLabel: "Flow Temperature (°C)",
    baseScopInfo: "Derived Base SCOP:",
    optimizationsTitle: "Additional Optimizations",
    optimizationsText: "Select optional components to refine the calculation.",
    fanEffectText: "With fans, the required flow temperature drops to",
    fanEffectScopText: "The SCOP thereby improves to",
    solarTypeLabel: "Collector Type",
    solarAreaLabel: "Collector Area of Solar System (m²)",
    solarYieldInfo: "Estimated Annual Yield",
    solarDisclaimer: "The yield reduces the heat demand the heating system must cover.",
    step3Title: "Step 3: Investment & Costs",
    investmentTitle: "Investment Costs & Funding for Heat Pump",
    investmentLabel: "Investment Costs for Heat Pump (incl. installation) in €",
    investmentDisclaimer: "Average: €15,000–€30,000. Add costs for additional optimizations.",
    fundingLabel: "Expected Subsidies (one-time) in €",
    fundingDisclaimer: "Reduces the effective investment costs.",
    runningCostsTitle: "Running Costs",
    maintenanceOldLabel: "Annual Maintenance Costs Old System (€)",
    maintenanceNewLabel: "Annual Maintenance Costs Heat Pump (€)",
    step4Title: "Step 4: Your Result",
    resultHeatDemand: "Usable Heat Demand (Old System)",
    resultCostsOld: "Current Heating Costs (Old System)",
    resultCo2Old: "CO₂ Emissions (Old System)",
    resultHpPower: "Approx. Heating Power of Heat Pump",
    resultCop: "Adjusted SPF/SCOP for HP",
    resultCostsNew: "Heating Costs with Heat Pump",
    resultCostsNewBuild: "Projected Annual Operating Costs",
    resultCo2New: "CO₂ Emissions (Heat Pump)",
    resultSavingsAnnual: "Annual Savings (Operating Costs)",
    resultSavingsCo2: "Annual CO₂ Savings",
    resultSavingsCo2Eq: "equals approx. {value} football fields of forest area per year.",
    resultAmortization: "Amortization Period (after funding)",
    unitYear: "year",
    unitYears: "years",
    fanResultLabel: "Effect of radiator fans",
    resultDisclaimer: "* All values are approximate guidelines. The recommended heating output is a rough estimate; a detailed heating load calculation by a specialist is essential for correct dimensioning.",
    exportPdfButton: "Export PDF",
    priceUpdateInfo: "The default energy prices in the calculator are estimates (as of June 2025) and should be checked against your current rates for an accurate calculation.",
    prevBtn: "Back",
    nextBtn: "Next",
    pdfExports: "PDF Exports",
    configId: "Configuration No.",
    amortizationNone: "No amortization",
    amortizationImmediate: "Immediately",
    amortizationNotApplicable: "Not applicable",
    pdfTitle: "Analysis of Your Heating Cost Savings",
    pdfInputsTitle: "Your Inputs",
    pdfResultsTitle: "Your Result",
    pdfFooter: "Calculation created on {date}. Configuration No.: {id}. All figures are estimates without guarantee.",
    commentaryTitle: "Interpretation of Results"
  },
  ro: {
    step1Title: "Pasul 1: Datele sistemului vechi",
    basisTitle: "Baza de calcul",
    basisText: "Vă rugăm să alegeți dacă calculul se va baza pe suprafața încălzită sau pe consumul anterior.",
    basisArea: "Calcul bazat pe suprafață",
    basisConsumption: "Calcul bazat pe consum",
    yourConsumptionTitle: "Consumul dvs.",
    annualConsumptionLabel: "Consum anual",
    yourPropertyTitle: "Imobilul dvs.",
    buildingClassLabel: "Clasa clădirii",
    areaLabel: "Suprafață încălzită (m²)",
    currentSystemTitle: "Sistemul dvs. actual de încălzire",
    efficiencyOldLabel: "Eficiența sistemului vechi (%)",
    efficiencyOldDisclaimer: "O valoare tipică este preselectată în funcție de sistemul de încălzire.",
    priceOldLabel: "Prețul actual pe unitate",
    step2Title: "Pasul 2: Sistem nou & Optimizare",
    heatpumpDataTitle: "Date pentru pompa de căldură",
    gridPriceLabel: "Prețul electricității din rețea pentru pompa de căldură (€/kWh)",
    gridPriceDisclaimer: "Acest preț se aplică și pentru \"Electricitate sistem vechi\".",
    floorHeatingShareLabel: "Procentul de încălzire prin pardoseală în distribuția căldurii (%)",
    floorHeatingShareDisclaimer: "Ajustat automat în funcție de clasa clădirii.",
    flowTempLabel: "Temperatura pe tur (°C)",
    baseScopInfo: "SCOP de bază derivat:",
    optimizationsTitle: "Optimizări suplimentare",
    optimizationsText: "Selectați componente opționale pentru a rafina calculul.",
    fanEffectText: "Cu ventilatoarele, temperatura necesară pe tur scade la",
    fanEffectScopText: "Astfel, SCOP-ul se îmbunătățește la",
    solarTypeLabel: "Tip colector",
    solarAreaLabel: "Suprafața colectorului solar (m²)",
    solarYieldInfo: "Producție anuală estimată",
    solarDisclaimer: "Producția reduce necesarul de căldură pe care trebuie să-l acopere sistemul de încălzire.",
    step3Title: "Pasul 3: Investiție & Costuri",
    investmentTitle: "Costuri de investiție & Finanțare pentru pompa de căldură",
    investmentLabel: "Costuri de investiție pentru pompa de căldură (inclusiv instalare) în €",
    investmentDisclaimer: "Medie: 15.000–30.000 €. Adăugați costurile pentru optimizări suplimentare.",
    fundingLabel: "Subvenții preconizate (unice) în €",
    fundingDisclaimer: "Reduce costurile efective de investiție.",
    runningCostsTitle: "Costuri de funcționare",
    maintenanceOldLabel: "Costuri anuale de întreținere sistem vechi (€)",
    maintenanceNewLabel: "Costuri anuale de întreținere pompa de căldură (€)",
    step4Title: "Pasul 4: Rezultatul dvs.",
    resultHeatDemand: "Necesar de căldură utilă (Sistem vechi)",
    resultCostsOld: "Costuri actuale de încălzire (Sistem vechi)",
    resultCo2Old: "Emisii de CO₂ (Sistem vechi)",
    resultHpPower: "Puterea de încălzire aprox. a pompei de căldură",
    resultCop: "SPF/SCOP ajustat pentru PC",
    resultCostsNew: "Costuri de încălzire cu pompa de căldură",
    resultCostsNewBuild: "Costuri anuale de operare estimate",
    resultCo2New: "Emisii de CO₂ (Pompa de căldură)",
    resultSavingsAnnual: "Economii anuale (Costuri de operare)",
    resultSavingsCo2: "Economii anuale de CO₂",
    resultSavingsCo2Eq: "echivalează cu aprox. {value} terenuri de fotbal de pădure pe an.",
    resultAmortization: "Perioada de amortizare (după subvenție)",
    unitYear: "an",
    unitYears: "ani",
    fanResultLabel: "Efectul ventilatoarelor de calorifer",
    resultDisclaimer: "* Toate valorile sunt orientative. Puterea de încălzire recomandată este o estimare brută; un calcul detaliat al sarcinii termice de către un specialist este esențial pentru o dimensionare corectă.",
    exportPdfButton: "Exportă PDF",
    priceUpdateInfo: "Prețurile implicite ale energiei din calculator sunt estimative (iunie 2025) și ar trebui verificate cu tarifele dvs. curente pentru un calcul precis.",
    prevBtn: "Înapoi",
    nextBtn: "Următorul",
    pdfExports: "Exporturi PDF",
    configId: "Nr. configurație",
    amortizationNone: "Fără amortizare",
    amortizationImmediate: "Imediat",
    amortizationNotApplicable: "Nu se aplică",
    pdfTitle: "Analiza economiilor la costurile de încălzire",
    pdfInputsTitle: "Datele dvs.",
    pdfResultsTitle: "Rezultatul dvs.",
    pdfFooter: "Calcul realizat la {date}. Nr. Configurație: {id}. Toate datele sunt estimări fără garanție.",
    commentaryTitle: "Interpretarea rezultatelor"
  }
};
